export assignOrdered from './assignOrdered'
export colorize from './colorize'
export deepMerge from './deepMerge'
export directionalScale, {isDirectional} from './directionalScale'
export getCSS from './getCSS'
export getIn from './getIn'
export getTheme from './getTheme'
export portalize from './portalize'
export supportsCSS from './supportsCSS'
export toSize from './toSize'
export withHoverQuery from './withHoverQuery'
