export defaultColors from './defaultColors'
export defaultHoverColors from './defaultHoverColors'
export defaultActiveColors from './defaultActiveColors'
export defaultTypeFaces from './defaultTypeFaces'
export injectTheme, {replaceTheme} from './injectTheme'
