export defaultColors from './defaultColors'
export defaultTypeFaces from './defaultTypeFaces'
export defaultRem from './defaultRem'
export injectTheme, {replaceTheme, curlsTheme} from './injectTheme'
export injectRem from './injectRem'
