export defaultColors from './defaultColors'
export defaultHoverColors from './defaultHoverColors'
export defaultActiveColors from './defaultActiveColors'
export defaultTypeFaces from './defaultTypeFaces'
export defaultRem from './defaultRem'
export injectTheme, {replaceTheme} from './injectTheme'
export injectRem from './injectRem'
